services:
  php:
    build: ./docker/php
    platform: linux/x86_64
    hostname: 'localhost'
    volumes:
      - ./:/usr/local/src/pcc:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /usr/local/src/pcc
